"""empty message

Revision ID: 4171aadb46e4
Revises: b311c0b93c9e
Create Date: 2024-04-03 13:29:19.881557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4171aadb46e4'
down_revision = 'b311c0b93c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('CartItemID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('MedicationID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['customer.CustomerID'], ),
    sa.ForeignKeyConstraint(['MedicationID'], ['medication.MedicationID'], ),
    sa.PrimaryKeyConstraint('CartItemID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    # ### end Alembic commands ###
