"""Add PasswordHash column to Customer model

Revision ID: b311c0b93c9e
Revises: 1c381aba91bd
Create Date: 2024-03-29 03:55:55.848566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b311c0b93c9e'
down_revision = '1c381aba91bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PasswordHash', sa.String(length=128), nullable=False))
        batch_op.drop_column('Password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Password', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('PasswordHash')

    # ### end Alembic commands ###
